sudo: required
services:
  - docker

before_install:
  - docker build -t dakshg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dakshg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "daksh-first-docker-react"
  env: "Dakshfirstdockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-407376397267"
  bucket_path: "daksh-first-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
